on:
  release:
    types: [published]
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: trigger_circleci
        id: oneHundred
        uses: circleci/trigger_circleci_pipeline@v1.0
        env:
          CCI_TOKEN: $
